[[main]]
  identifier = "about"
  name = "About"
  url = "about"
  weight = 1

[[main]]
  identifier = "publication"
  name = "Publication"
  url = "tags/publication"
  weight = 2
  
[[main]]
  identifier = "code"
  name = "Code"
  url = "tags/code"
  weight = 3
  
[[main]]
  identifier = "animation"
  name = "Animation"
  url = "tags/animation"
  weight = 4


[[main]]
  identifier = "gallery"
  name = "Gallery"
  url = "gallery"
  weight = 6
    
[[main]]
  parent = "gallery"
  name = "Food"
  url = "gallery/food"

[[main]]
  parent = "gallery"
  name = "Photo"
  url = "gallery/photo"


[[main]]
  identifier = "archive"
  name = "Archive"
  url = "archive"
  weight = 7

[[main]]
  identifier = "github"
  name = "Github"
  url = "https://github.com/ttnghia"
  weight = 8
