[[main]]
  identifier = "about"
  name = "About"
  url = "about"
  weight = 1

[[main]]
  identifier = "publication"
  name = "Publication"
  url = "tags/paper"
  weight = 2
  
[[main]]
  identifier = "code"
  name = "Code"
  url = "tag/code"
  weight = 3
  
[[main]]
  identifier = "blog"
  name = "Blog"
  url = "tag/blog"
  weight = 4

[[main]]
  identifier = "gallery"
  name = "Gallery"
  url = "gallery"
  weight = 5
    
[[main]]
  parent = "gallery"
  name = "Food"
  url = "gallery/food"

[[main]]
  parent = "gallery"
  name = "Photo"
  url = "gallery/photo"


[[main]]
  identifier = "archive"
  name = "Archive"
  url = "archive"
  weight = 6
