# Site settings
title: Nghia Truong's graphics works
description: Graphics is awesome.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://ttnghia.github.io" # the base hostname & protocol for your site
twitter_username: nghiatruong_vn
github_username:  ttnghia
update-time: Updated Jan. 2017
# Build settings
markdown: kramdown
permalink: pretty
google_analytics: UA-34491264-2