# Site settings
title: Nghia Truong's awesome site
description: > # this means to ignore newlines until "baseurl:"
Graphics is awesome.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://ttnghia.github.io" # the base hostname & protocol for your site
twitter_username: nghiatruong_vn
github_username:  ttnghia
update-time: Jan. 2017
# Build settings
markdown: kramdown
permalink: pretty
