# baseurl = "http://localhost:8000/"
baseurl = "https://ttnghia.github.io/"
title = "Nghia Truong"
theme = "hugo-creative-portfolio-theme"
languageCode = "en-us"
# Enable comments by entering your Disqus shortname
disqusShortname = ""
# Enable Google Analytics by entering your tracking code
googleAnalytics = "UA-34491264-2"

[params]
  # Style options: default (pink), blue, green, pink, red, sea, violet
  # Use custom.css for your custom styling
  style = "sea"
  description = "Nghia Truong's personal website"
  copyright = "&copy;2018 by Nghia Truong | Template by Hugo"
  sidebarAbout = [
    "<img src='/img/about.png' style='width: 80%;'/>",
    "I am a graphics and computer and food enthusiast with more than 10 years of programming experience and more than 30 years of eating experience."
  ]
  # Contact page
     # Since this template is static, the contact form uses www.formspree.io as a
     # proxy. The form makes a POST request to their servers to send the actual
     # email. Visitors can send up to a 1000 emails each month for free.
     #
     # What you need to do for the setup?
     #
     # - set your email address under 'email' below
     # - upload the generated site to your server
     # - send a dummy email yourself to confirm your account
     # - click the confirm link in the email from www.formspree.io
     # - you're done. Happy mailing!
  email = "nghiatruong.vn@gmail.com"

  # Nav links in the side bar
  [[params.navlinks]]
  name = "Home"
  url = ""
 
  [[params.navlinks]]
  name = "About"
  url = "about/"
  
  [params.social]
  twitter       = "https://twitter.com/nghiatruong_vn"
  linkedin      = "https://www.linkedin.com/in/nghia-truong-85971422/"
  github        = "https://github.com/ttnghia"
